### ISSUE TITLE
Initial body text not colored if xcolor is loaded and last header content is colored in text color

### ISSUE THREAD

**Issue by zauguin** [ho-tex/luacolor#2]
Take

```
\documentclass{book}
\usepackage{xcolor}
\usepackage{luacolor}
\begin{document}
\makeatletter
\def\@evenhead{\color{red}\thepage\hfil\slshape\leftmark}%
\def\@oddhead{\color{red}{\slshape\rightmark}\hfil\thepage}%
\makeatother
\color{red}abc
\end{document}
```

Here `abc` isn't colored because `luacolor` detects that the color does not change between `\thepage` in the head and `abc`, but `xcolor` resets the color at the beginning of the text block, so `abc` ends up black.

Initially report in a [luaotfload PR comment](https://github.com/latex3/luaotfload/pull/135#issuecomment-593670373) by @dohyunkim.

**Comment by u-fischer** [comment]
Hm. I guess the concrete problem shouldn't be difficult to resolve. But I had a similar problem in the tagpdf code and so in general it would be probably good if the output routine would mark the various components (header, footer) so that the traversing code can handle them independently.

**Comment by zauguin** [comment]
@u-fischer I fully agree that such markup in the output routine would be good, but I think that this should be fixed more generally. The actual issue here is that `xcolor` calls `\color{black}` before `luacolor` is loaded and therefore inserts a colorstack whatsit. I think that this is a `xcolor` bug (Explicitly setting black might be useful if some special colorspace is used or similar but the current approach would fail to color the first header consistently) but there might be other uses for explicitly using `\pdfextension colorstack {push,set}`.

I think luacolor should detect this and either use the color for cases where no color is set as far as `luacolor` is concerned or issue a warning and drop these commands.
