### ISSUE TITLE
\mathcolor eats a token

### ISSUE THREAD

**Issue by u-fischer** [ho-tex/luacolor#7]
As in luacolor `\reset@color` isn't use a \mathcolor in a group eats a token:

```
\documentclass{article}
\usepackage{luacolor}
\begin{document}

${\mathcolor{red}{a}}bc$

\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/218731586-0d5d52c0-f213-4678-b24c-650124d5a551.png)

A work around

~~~~
\makeatletter
\protected\def\set@color{%
  \LuaCol@setattribute\LuaCol@Attribute{%
    \directlua{%
      oberdiek.luacolor.get("\luaescapestring{\current@color}")%
    }%
  }%
  \aftergroup\reset@color
}
\makeatother
~~~~

**Comment by davidcarlisle** [comment]
Yes I guess so. Longer term I suppose it would make more sense for `\mathcolor` not to gobble in cases where there is nothing to gobble, but while the code is distributed over multiple packages, probably simpler to bring them all in to line as you suggest

**Comment by RealChefSalad** [comment]
I have had this problem as well, although it would always cause an error for me. I, too, tracked it down to mathcolor eating a token, but it doesn't do this when luacolor isn't used. Here's my minimal code for getting this problem.

```
\documentclass{minimal}
\usepackage{luacolor}
\normalfont\rmfamily
\renewcommand\normalsize{\fontsize{10pt}{12pt}\selectfont}

\begin{document}
asdf
\( \mathcolor{red}{jjjj} \)
\end{document}

```

**Comment by davidcarlisle** [comment]
@RealChefSalad  yes that is fixed by the code @u-fischer  suggests above if you add it to the preamble

**Comment by u-fischer** [comment]
@davidcarlisle  I had forgotten this. Should we add it to luacolor?

**Comment by davidcarlisle** [comment]
@u-fischer  we could although i'm tempted to say instead luacolor should redefine mathcolor not to have the use:none

**Comment by davidcarlisle** [comment]
we should fix it somehow though

**Comment by u-fischer** [comment]
it feels safer to simply change \@setcolor, it is redefined anyway, instead of adding a patch of another command that one would have to track.

**Comment by davidcarlisle** [comment]
@u-fischer  OK, although my thought was based on this mathcolor comment

```
%    Then we switch to the new color, but we do not want to reset the
%    color after the group (which is done by \cs{color} using
%    \cs{aftergroup}\cs{reset@color}). The best solution here would be
%    if the color packages  would provide a command doing just the
%    color switching, but for now we simply undo that part by pushing
%    \cs{use_none:n} which gobbles the \cs{reset@color} added by
%    \cs{color} with \cs{aftergroup}.
```

luacolor is doing exactly that: providing a color without an aftergrouped restore, but as you say for now adding a restore token minimises differences.

**Comment by u-fischer** [comment]
yes I saw that, but I think that it is more consistent if `\@setcolor` resets the color (even if that is not needed) in luacolor too, and then we can think about a `\@setbutdonotresetcolor` command ...

**Comment by davidcarlisle** [comment]
OK you or me?

**Comment by u-fischer** [comment]
I uploaded a new version to ctan which fixes this issue.
